# Use bash-completion, if available
alias bitcoind="/home/ubuntu/mining-setup/bin/bitcoind"
alias bitcoin-qt="/home/ubuntu/mining-setup/bin/bitcoin-qt"
alias bitcoin-util="/home/ubuntu/mining-setup/bin/bitcoin-util"
alias bitcoin-tx="/home/ubuntu/mining-setup/bin/bitcoin-tx"
alias bitcoin-wallet="/home/ubuntu/mining-setup/bin/bitcoin-wallet"
alias test_bitcoin="/home/ubuntu/mining-setup/bin/test_bitcoin"
alias test_bitcoin-qt="/home/ubuntu/mining-setup/bin/test_bitcoin-qt"
alias bitcoin-cli="bitcoin-cli -datadir=/bitcoind"
alias cli="/home/ubuntu/mining-setup/bin/cli"

[[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && \
    . /usr/share/bash-completion/bash_completion
